controller_list:
  - name: fake_mh5_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_s
      - joint_l
      - joint_u
      - joint_r
      - joint_b
      - joint_t
initial:  # Define initial robot poses.
  - group: mh5
    pose: Home